### ISSUE TITLE
Glitching models

### ISSUE THREAD

**Issue by soler91** [VenoMKO/Real-Editor#2]
I've been using this tool for some days but every single model that i import always has some wild vertices that glitch everywhere, even if it's just as simple as a simple unwrapped cube...

My process so far is
Export fbx with bones
Import to an empty scene in blender 2.79b
Edit the mesh
Remove doubles
Recalculate normals
Export fbx and import in RE

I made sure that it only had one UV set and even took all the textures and removed their alpha channels

Am i doing anything wrong or just unlucky ?

**Comment by VenoMKO** [comment]
Sounds like a blend weight issue. Make sure you rigged your model properly

**Comment by soler91** [comment]
Tried another 30ish times, even reskining the model still same...
i'm starting to think it has something to do with the way i'm exporting back to fbx from blender because i can export fbx from RE and then import that same one and the new gpk works fine in game...
have u imported anything using blender 2.79b lately ? if u even use blender for this that is lol

**Comment by soler91** [comment]
Aaaaand i tried exporting the edited mesh from blender to RE then from RE to fbx and imported that fbx and it's fixed ???? i'm confused but it works now
